# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gcodesenderui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GCodeSenderUI(object):
    def setupUi(self, GCodeSenderUI):
        GCodeSenderUI.setObjectName("GCodeSenderUI")
        GCodeSenderUI.resize(630, 454)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GCodeSenderUI.sizePolicy().hasHeightForWidth())
        GCodeSenderUI.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(GCodeSenderUI)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 611, 221))
        self.tabWidget.setObjectName("tabWidget")
        self.tabConnect = QtWidgets.QWidget()
        self.tabConnect.setObjectName("tabConnect")
        self.portSelect = QtWidgets.QComboBox(self.tabConnect)
        self.portSelect.setGeometry(QtCore.QRect(90, 60, 161, 22))
        self.portSelect.setObjectName("portSelect")
        self.bdrateSelect = QtWidgets.QComboBox(self.tabConnect)
        self.bdrateSelect.setGeometry(QtCore.QRect(90, 100, 161, 22))
        self.bdrateSelect.setObjectName("bdrateSelect")
        self.connectButton = QtWidgets.QPushButton(self.tabConnect)
        self.connectButton.setGeometry(QtCore.QRect(320, 60, 181, 61))
        self.connectButton.setObjectName("connectButton")
        self.tabWidget.addTab(self.tabConnect, "")
        self.tabOneLine = QtWidgets.QWidget()
        self.tabOneLine.setObjectName("tabOneLine")
        self.lineEdit = QtWidgets.QLineEdit(self.tabOneLine)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 470, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.sendLineButton = QtWidgets.QPushButton(self.tabOneLine)
        self.sendLineButton.setGeometry(QtCore.QRect(490, 40, 100, 25))
        self.sendLineButton.setObjectName("sendLineButton")
        self.tabWidget.addTab(self.tabOneLine, "")
        self.tabFile = QtWidgets.QWidget()
        self.tabFile.setObjectName("tabFile")
        self.progressBar = QtWidgets.QProgressBar(self.tabFile)
        self.progressBar.setGeometry(QtCore.QRect(10, 150, 581, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.selectFileButton = QtWidgets.QPushButton(self.tabFile)
        self.selectFileButton.setGeometry(QtCore.QRect(10, 20, 93, 25))
        self.selectFileButton.setObjectName("selectFileButton")
        self.sendgcodeButton = QtWidgets.QPushButton(self.tabFile)
        self.sendgcodeButton.setGeometry(QtCore.QRect(10, 60, 93, 25))
        self.sendgcodeButton.setObjectName("sendgcodeButton")
        self.filePath = QtWidgets.QLineEdit(self.tabFile)
        self.filePath.setGeometry(QtCore.QRect(110, 20, 471, 25))
        self.filePath.setObjectName("filePath")
        self.lineCurrent = QtWidgets.QLineEdit(self.tabFile)
        self.lineCurrent.setEnabled(True)
        self.lineCurrent.setGeometry(QtCore.QRect(10, 100, 571, 22))
        self.lineCurrent.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineCurrent.setMouseTracking(True)
        self.lineCurrent.setAutoFillBackground(False)
        self.lineCurrent.setFrame(False)
        self.lineCurrent.setReadOnly(True)
        self.lineCurrent.setObjectName("lineCurrent")
        self.tabWidget.addTab(self.tabFile, "")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 240, 611, 171))
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setObjectName("textBrowser")
        GCodeSenderUI.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(GCodeSenderUI)
        self.mainToolBar.setObjectName("mainToolBar")
        GCodeSenderUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(GCodeSenderUI)
        self.statusBar.setObjectName("statusBar")
        GCodeSenderUI.setStatusBar(self.statusBar)

        self.retranslateUi(GCodeSenderUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GCodeSenderUI)

    def retranslateUi(self, GCodeSenderUI):
        _translate = QtCore.QCoreApplication.translate
        GCodeSenderUI.setWindowTitle(_translate("GCodeSenderUI", "GCodeSenderUI"))
        self.connectButton.setText(_translate("GCodeSenderUI", "Connect!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConnect), _translate("GCodeSenderUI", "Page"))
        self.sendLineButton.setText(_translate("GCodeSenderUI", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOneLine), _translate("GCodeSenderUI", " Single Line"))
        self.selectFileButton.setText(_translate("GCodeSenderUI", "Select File"))
        self.sendgcodeButton.setText(_translate("GCodeSenderUI", "Send GCode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFile), _translate("GCodeSenderUI", "File"))

